# Generated by Django 4.1.4 on 2023-06-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundsintel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentfund',
            old_name='information_adm_fee',
            new_name='adm_fee_information',
        ),
        migrations.RenameField(
            model_name='investmentfund',
            old_name='information_performance_fee',
            new_name='performance_fee_information',
        ),
    ]
