# Generated by Django 4.1.4 on 2023-06-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundsintel', '0003_rename_cnpj_adm_investmentfund_adm_cnpj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentfund',
            old_name='dt_update',
            new_name='dt_updated',
        ),
        migrations.RenameField(
            model_name='investmentfund',
            old_name='pf_pj_manager',
            new_name='manager_pf_pj',
        ),
    ]
